[FIX] Build errors
ramad@Itadori MINGW64 /d/Project/drawing-apps/lottery-v2 (refactor-mechanism)
$ npm run build

> lottery-app@1.0.0 build
> tsc -b && vite build

src/components/draw/PrizeWinnersModal.tsx:21:10 - error TS6133: 'StatusBadge' is declared but its value is never read.

21 function StatusBadge({ status }: { status: string }) {
            ~~~~~~~~~~~

src/components/draw/WinnerGallery.tsx:108:13 - error TS2322: Type 'DrawResult & { id?: string | undefined; }' is not assignable to type 'DrawResultWithId'.
  Types of property 'id' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.

108             winner={winner}
                ~~~~~~

  src/components/draw/WinnerCard.tsx:12:3
    12   winner: DrawResultWithId
         ~~~~~~
    The expected type comes from property 'winner' which is declared here on type 'IntrinsicAttributes & WinnerCardProps'

src/pages/DrawScreen.tsx:123:23 - error TS6133: 'setIsRedrawing' is declared but its value is never read.

123   const [isRedrawing, setIsRedrawing] = useState(false)
                          ~~~~~~~~~~~~~~

src/pages/DrawScreen.tsx:139:5 - error TS6133: 'hasCancelled' is declared but its value is never read.

139     hasCancelled,
        ~~~~~~~~~~~~

Found 4 errors.